// Error Heading -> try,catch,finally,throw
// try....catch handle run time error
// Error object
// the finally statement-> execute code

try{
    // code test
    alert('hi everyone');
    alert(x);
    alert('Bye everyone');
}catch(err){
    // handle error
    alert('Inside catch');
    console.log(err);
    console.log(err.name);
    console.log(err.massage);
}finally{
    alert('Bye everyone');
}



// alert('hi everyone');
// alert(x);
// alert('Bye everyone');









